### ISSUE TITLE
Switch KPL to Aggregation by google-protobuf

### ISSUE THREAD

**Issue by riywo** [awslabs/aws-fluent-plugin-kinesis#107]
Delete KPL dependency and add feature to aggregate by `google-protobuf`

**Comment by riywo** [comment]
Initial implementation has been finished and worked. It has limits; supporting only random or fixed partition key only, supporting fixed stream name only.

**Comment by riywo** [comment]
#112

**Comment by wryun** [comment]
Totally missed this - thanks! I'll keep an eye out for 2.0, and redirect people in the README for fluent-kinesis-aggregation.
