### ISSUE TITLE
kinesis_producer can't refresh AssumeRole Credential.

### ISSUE THREAD

**Issue by tatsu-yam** [awslabs/aws-fluent-plugin-kinesis#108]
The kinesis_producer plugin got into the state which can't refresh AssumeRole Credential in our environment. (https://github.com/awslabs/aws-fluent-plugin-kinesis/issues/58)
Even though, we use fluent-plugin-kinesis 1.0.1 (or later version).

Our setting is below
+ version
    + td-agent 2.3
    + fluent-plugin-kinesis 1.0.1 (or later version)
+ td-agent.conf
```
<match hoge>
  @type kinesis_producer
  stream_name  xxx
  region ap-northeast-1
  <assume_role_credentials>
    role_arn    xxxxxxxxxx
    external_id xxxxxxxxxx
  </assume_role_credentials>
  time_format %s
  include_time_key true
  buffer_type file
  buffer_path /var/log/td-agent/buffer/kinesis
  buffer_chunk_limit 500k
  buffer_queue_limit 16384
  flush_interval 1s
  try_flush_interval 0.1s
  queued_chunk_flush_interval 0.01s
  num_threads 4
</match>
```

When an exeception occurs in the `KinesisProducer::Daemon#updaet_credentials`, the thread which calls `#update_credentials` seems to die. ( https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/75e8a34f9be2eff20e15a1f5a62f8a52efc1d9b7/lib/kinesis_producer/daemon.rb#L159 )

I tried deleting a policy from an IAM Role which the EC2 Instance assumes.
As a result, `KinesisProducer::Daemon#update_credentials` was not called every `credentials_refresh_delay` second.

When I added the code which rescues a Exception `add(make_set_credentials_message)` throws, even if its policy was changed, `#update_credentials` was called regularly.

But I don't know why that method is failed in our environment.

**Comment by riywo** [comment]
Hi @tatsu-yam ,

Thank you for reporting. I'll look into this.

**Comment by riywo** [comment]
I'm sorry for no response for a long time. We're are going to release [v2.0.0](https://github.com/awslabs/aws-fluent-plugin-kinesis/pull/112) which supports record aggregation by a different way without KPL. So, this problem never happen and I'm closing.

Please try v2.0.0 first. If you need more help, feel free to add comment.
