### ISSUE TITLE
feedback for fluent-plugin-kinesis version 2.

### ISSUE THREAD

**Issue by tatsu-yam** [awslabs/aws-fluent-plugin-kinesis#116]
Current fluentd stable version is v0.12 ( td-agent version 2), so I want to use next version this plugin with it.

**Comment by riywo** [comment]
Hi @tatsu-yam ,

Thank you for your feedback. I'll check this to work with fluentd v0.12 once the major capabilities are fixed with v0.14 during preview of v2.0.

Best,
Ryoske

**Comment by davidgacc** [comment]
@riywo plugin-kinesis works with fluentd 0.14 ?

**Comment by riywo** [comment]
Hi @davidgacc ,

Sorry for delay of my response. v2 is intended to be used by fluentd 0.14. v1 is for fluentd 0.12, but as long as 0.14 supports 0.12 compatibility, it might work with 0.14.

**Comment by riywo** [comment]
Released https://rubygems.org/gems/fluent-plugin-kinesis/versions/2.0.0.rc.1.1 supporting fluentd v0.12.35 or later.
