### ISSUE TITLE
Kinesis Consumer Library integration

### ISSUE THREAD

**Issue by rgarcia** [awslabs/aws-fluent-plugin-kinesis#117]
Is there a way to write a KCL app using this plugin? We have been successful using this plugin's KPL integration to produce data into Kinesis. It would be great to be able to consume the KPL-aggregated data that this plugin produces and then forward it along using existing Fluentd plugins.

**Comment by riywo** [comment]
Hi @rgarcia ,

Unfortunately, this plugin only supports output plugin, not input. You need a separate plugin for such use case.

Best,
