### ISSUE TITLE
support for placeholder expansion

### ISSUE THREAD

**Issue by zellski** [awslabs/aws-fluent-plugin-kinesis#119]
Greetings,

It's possible I simply don't understand exactly how placeholder expansion works, but I would very much like to be able to specify e.g.
`
  stream_name ${tag_parts[1]}
`
Is this reasonably doable?

**Comment by riywo** [comment]
Hi @zellski ,

Sorry for my late response. The plugin itself doesn't support dynamic stream_name. You might use forest plugin, instead. https://github.com/tagomoris/fluent-plugin-forest
