### ISSUE TITLE
shared credentials are not read correctly

### ISSUE THREAD

**Issue by ddehghan** [awslabs/aws-fluent-plugin-kinesis#137]
Hi everyone, it seems that shared_credentials are not read. 

This works:

```
<match **>
    @type kinesis_streams

    region us-east-1
    stream_name my-events

    aws_key_id ABCDABCDABCDABCDABCD
    aws_sec_key ABCDABCDABCDABCDABCD
</match>
```

but this does not:

```
<match **>
    @type kinesis_streams

    region us-east-1
    stream_name my-events

    <shared_credentials>
        path "/root/.aws/credentials" 
        profile_name "default"
    </shared_credentials>
</match>
```

The error I get is:

2017-12-28 11:57:00 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2017-12-28 11:57:00 +0000 chunk="56165330c8394f1cd27763bd24c03400" error_class=NoMethodError error="undefined method `access_key_id' for nil:NilClass"

credential file is at /root/.aws/credentials
```
-rw-r--r-- 1 root root 112 Dec 28 11:52 /root/.aws/credentials


[default]
aws_access_key_id=ABCDABCDABCDABCDABCD
aws_secret_access_key=ABCDABCDABCDABCDABCD
```

Happy Hollidays. :-)

**Comment by simukappu** [comment]
Does anyone have a same issue?

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.

**Comment by later123** [comment]
I got the same issue, could you please share how to resolve it?

**Comment by mostfunkyduck** [comment]
also having this issue

**Comment by ravinaik1312** [comment]
@qinqin-wang @mostfunkyduck Make sure the `td-agent` process has the permission to read your credentials file. The error handling could improve, but it needs to bubble up at the `aws-ruby-sdk` which this plugin is using.
