### ISSUE TITLE
Partition Key is empty for fluent agent's logs

### ISSUE THREAD

**Issue by Resisty** [awslabs/aws-fluent-plugin-kinesis#138]
Because reasons™ I'm stuck on:

- ruby 1.9.3
- aws-sdk-core v2.7.0
- fluentd v0.12.40
- aws-fluent-plugin-kinesis v0.4.1

Using the in_tail plugin to send items to Kinesis Streams works fine. However, trying to send the fluentd agent's own logs fails; the configuration:

```
<filter fluent.**>
  @type             record_transformer
  enable_ruby
  <record>
    gen_host          "#{Socket.gethostname}"
  </record>
</filter>
<filter fluent.**>
  @type stdout
</filter>
<match fluent.**>
  @type                kinesis
  stream_name          fluentd-agent
  partition_key        gen_host
  include_time_key     true
  @id                  fluentd-agent-kinesis
  append               true
  time_slice_format    %Y%m%d
  time_slice_wait      1m
  time_format          %Y%m%dT%H%M%S%z
  buffer_type          file
  buffer_path          /tmp/log/fluentd-agent.*.buffer
  tag                  fluentd-agent
  flush_interval       10s
</match>
```

should, as far as I'm aware, add a `gen_host` field to each record matching tag `fluent.**` and then get sent to Kinesis. This is almost verbatim for the `in_tail` sources I've configured except for the `stream_name`, `@id` (which I changed to verify this was the config stanza that was having problems), `buffer_path`, and `tag` values, which are all generated via template and differ between actually-working streams as well.

What actually happens is warnings like this and no data being sent to Kinesis:

```
2018-01-03 10:02:36 -0800 [warn]: temporarily failed to flush the buffer. next_retry=2018-01-03 11:13:34 -0800 error_class="Aws::Kinesis::Errors::ValidationException" error="1 validation error detected: Value '' at 'records.1.member.partitionKey' failed to satisfy constraint: Member must have length greater than or equal to 1" plugin_id="fluentd-agent-kinesis"
```

Somewhat bizarrely, when I switch it from `<filter fluent.**>`, direct logs to a file, and then _tail that log with `in_tail`_, it does the same thing.

If anybody has any insight into this, I'd very much appreciate it. Thanks!

**Comment by simukappu** [comment]
Fluentd v0.12.40 is not supported in plugin v3.
Closing this issue for now. Please reopen if required.
