### ISSUE TITLE
it is calculating the wrong record size on batch request.

### ISSUE THREAD

**Issue by tamtam180** [awslabs/aws-fluent-plugin-kinesis#141]
## (FYI) on v0.3.4 (sorry for too old version)

I’m using this version. And I got error of `Records size exceeds 5 MB limit`.
This is because `[put_records](https://docs.aws.amazon.com/ja_jp/kinesis/latest/APIReference/API_PutRecords.html)` data size should under 5MB include `partition_key`, but this version does not include `partition_key`.

Under my case, it wrote 470 records with { data = 5239177 bytes, data + partition_key = 5250457 bytes}. So, 5239177 is less than 5242880, but 5250457 is greater than API Limit(5242880).

Please never mind, because it is an old version.

## on v2.1.1 (latest version)

I have try to upgrade this version from 0.3.4.
This plugin support fluentd-0.12.35+ (on README).

**I try to use Ruby2.3.x + fluentd-0.12.35**
I got error that no method of record(Hash) compact on [this code](https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/e08d3896eb292cd76c7ba8b19c0b41b77e9fffa9/lib/fluent/plugin/kinesis_helper/api.rb#L67).

**I try to use Ruby 2.4.x + fluentd-0.12.35**
I got same error `Records size exceeds 5 MB limit`.

I think, [following code](https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/v2.1.1/lib/fluent/plugin/kinesis_helper/api.rb#L67) is looks like a wrong calculation.

    def size_of_values(record)
        record.compact.map(&:size).inject(:+) || 0
    end

Because:

    record.compact.map do |x|
      # x is `[k,v]`, and x.size is `2`
    end

And, `write` method on `out_kinesis_streams.rb`. 
This also seems to be incorrect.

        def write(chunk)
          write_records_batch(chunk) do |batch|
            records = batch.map{|(data, partition_key)|
              { data: data, partition_key: partition_key }
            }
            # I dumped records[0], partition_key is null. and data["partition_key"] is filled. 
            # { :data => { 
            #   "data" => "string",
            #   "partition_key" => "filed"
            #   },
            # :partition_key => nil
            # }
            client.put_records(
              stream_name: @stream_name,
              records: records,
            )
          end

Is my environment strange? or wrong code?
Thanks,

**Comment by simukappu** [comment]
Thank you for your reporting. The plugin v3 will remove support for Fluentd 0.12.
Closing this issue for now. Please reopen if required.
