### ISSUE TITLE
chomp is removing trailing newlines.

### ISSUE THREAD

**Issue by burkaygur** [awslabs/aws-fluent-plugin-kinesis#142]
https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/lib/fluent/plugin/kinesis.rb#L108

Here, the additional formatting - chomp - is causing newlines to be removed that the JSON formatter is adding by default. I think at this point we should rely on the formatter and not do any post-processing.

**Comment by riywo** [comment]
Just released v3.0.0.rc.2.0 which doesn't `chomp` by default. Please try it out and give us feedback! https://rubygems.org/gems/fluent-plugin-kinesis/versions/3.0.0.rc.2.0

**Comment by simukappu** [comment]
We will publish v3.0.0 next week unless we get any trouble feedback. We are appreciate your patience.

**Comment by riywo** [comment]
Today, we've released v3.0.0 in rubygems. https://rubygems.org/gems/fluent-plugin-kinesis/versions/3.0.0
