### ISSUE TITLE
Fluentd v1.x support?

### ISSUE THREAD

**Issue by Trane9991** [awslabs/aws-fluent-plugin-kinesis#147]
Does the plugin support usage of fluentd > 1.0.0?

**Comment by simukappu** [comment]
Yes, the plugin is tested with these td-agent (fluentd) versions.
https://github.com/awslabs/aws-fluent-plugin-kinesis/tree/master/gemfiles

Please see also [README.md](https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/README.md).

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
