### ISSUE TITLE
Fluentd Conflict

### ISSUE THREAD

**Issue by spsusbilla** [awslabs/aws-fluent-plugin-kinesis#15]
We have recently encountered this error:

"Unable to activate fluent-plugin-kinesis-0.3.0, because fluentd-0.12.2 conflicts with fluentd (< 0.11, >= 0.10.53) (Gem::LoadError),"

is there any reason why the plugin is only compatible to fluentd versions up to 0.11 only? Please advise.

Thanks.

**Comment by imaifactory** [comment]
Hi @spsusbilla 

Thank you for reporting.
Fluentd version0.12 is a kind of major update from 0.10 so we do not support v0.12. However, after clarification, we will support v0.12. Please wait our next update. However if you in a hurry, you can modify gemspec file to support Fluentd v0.12 and try to use.

Thanks

**Comment by spsusbilla** [comment]
Thanks for the prompt response @imaifactory.

What I did was routed the data to an instance with a lower version of Fluentd, but will try to test it as you suggested. Either way, we'll be patiently waiting for the next update.

Thanks.

**Comment by imaifactory** [comment]
@spsusbilla Sorry about late update. We now support fluentd version 0.12 https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/fluent-plugin-kinesis.gemspec#L37

Thanks.

**Comment by spsusbilla** [comment]
@imaifactory yay! Thanks for this.
