### ISSUE TITLE
Publish to RubyGems

### ISSUE THREAD

**Issue by edjames** [awslabs/aws-fluent-plugin-kinesis#16]
Any idea when you plan on making this available via RubyGems?

**Comment by edjames** [comment]
Bump. It would be very helpful if someone could please give some kind of timeline as to if/when this will be available via rubygems.
It makes server installation a real pain having to follow a multi-step, manual process.

Many thanks.

**Comment by imaifactory** [comment]
Thank you. I will try on this.

**Comment by edjames** [comment]
Thanks. As an aside, I found that instead of running the installation steps
on the server, it's easier to build the gem locally and add the gem file to
my Chef recipe as a static file. I then only have to run a single command
to install the plugin on my server.

On Friday, March 27, 2015, Yuta Imai <notifications@github.com> wrote:

> Thank you. I will try on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awslabs/aws-fluent-plugin-kinesis/issues/16#issuecomment-86894557>
> .
>


-- 
------------------------------
Ed James
ed.james.email@gmail.com
+44.7816.572.706

  <https://twitter.com/grokling>
<https://plus.google.com/103002300182822334722/posts>

**Comment by imaifactory** [comment]
Hi @edjames thank you for waiting.
I am still working on this, however it may take time.
Thank you for understanding and giving us request.

**Comment by imaifactory** [comment]
@edjames Thank you for patience. It is live now. https://rubygems.org/gems/fluent-plugin-kinesis
