### ISSUE TITLE
How to use buffer file for reliability ?

### ISSUE THREAD

**Issue by doubret** [awslabs/aws-fluent-plugin-kinesis#164]
Is this plugin buffered ?
I would like to use a file for buffering the logs before they are sent to kinesis in case something goes wrong.
Do you have an example of using a buffer file with the plugin ?
Thanks

**Comment by janerikcarlsen** [comment]
I'm also curious about this

**Comment by cosmo0920** [comment]
You can use [file buffer](https://docs.fluentd.org/v0.12/articles/buf_file) to protect processing buffer:

```aconf
<match your_tag>
  @type kinesis_streams
  region us-east-1
  stream_name your_stream
  partition_key key  # Otherwise, use random partition key
  buffer_type file
  buffer_path /path/to/your/buffer
</match>
```

**Comment by simukappu** [comment]
Thank you @cosmo0920 for answering. Closing this issue for now. Please reopen if required.
