### ISSUE TITLE
Adding EC2 metadata

### ISSUE THREAD

**Issue by mitrilmad** [awslabs/aws-fluent-plugin-kinesis#168]
I am trying to send kinesis by using this plugin. It would be better If I could add ec2-metadata.
Is there any way to add some ec2-meta information?

**Comment by cosmo0920** [comment]
You can use [fluent-plugin-ec2-metadata plugin](https://github.com/takus/fluent-plugin-ec2-metadata). :)

**Comment by simukappu** [comment]
Thank you @cosmo0920 for answering. Closing this issue for now. Please reopen if required.
