### ISSUE TITLE
File Buffering

### ISSUE THREAD

**Issue by spsusbilla** [awslabs/aws-fluent-plugin-kinesis#17]
Any plans of adding this feature in the future?

**Comment by imaifactory** [comment]
Hello @spsusbilla 
This plugin is [based on BufferedPlugin](https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/lib/fluent/plugin/out_kinesis.rb#L21).
I believe you can use file buffer now.
http://docs.fluentd.org/articles/buffer-plugin-overview#buffer-structure

**Comment by spsusbilla** [comment]
Oh, I'm sorry @imaifactory, I'm an idiot. I really missed this one. Somehow I kept remembering that I tested this before and it says it isn't used, that's why I'm not implementing this in our deployment.

Thanks and sorry for the trouble.
