### ISSUE TITLE
how to verrify comrpression working correctly?

### ISSUE THREAD

**Issue by tj13** [awslabs/aws-fluent-plugin-kinesis#175]
how can i to verify whether gzip compression is working? the config is as below

`<match tomcat.syslog>
  @type kinesis_streams
  compression zlib 
  region cn-north-1 
  stream_name test
  @log_level info
  flush_interval 1
</match>
`

**Comment by tj13** [comment]
`<match tomcat.syslog>
  @type kinesis_streams
  compression zlib 
  region cn-north-1 
  stream_name test
  @log_level info
  flush_interval 1
</match>
`

**Comment by simukappu** [comment]
You can verify by checking consumed data. The following test code may be helpful for you.
https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/test/plugin/test_kinesis.rb#L79-L88

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
