### ISSUE TITLE
Is it possible to use ${tag} in the delivery_stream_name

### ISSUE THREAD

**Issue by nehiljain** [awslabs/aws-fluent-plugin-kinesis#184]
Similar to https://github.com/fluent/fluent-plugin-s3#v10-style I want to dynamically send events to different firehose streams. Is it possible to use that with fluentd-kinesis plugin

**Comment by simukappu** [comment]
Currently, you cannot use ${tag} in the stream_name. This request seems to be same as #174.

**Comment by simukappu** [comment]
Closing this issue for now since it's duplicate. Please reopen if required.
