### ISSUE TITLE
Any load/stress testing has been done for the plugin?

### ISSUE THREAD

**Issue by Nikunj-Sharma** [awslabs/aws-fluent-plugin-kinesis#185]
Hi There,

Let me first apologies for posting a question here, But unable to find any answer anywhere else.
Thanks a lot for this wonderful plugin. I was wondering that what kind of load plugin can handle.
We have a scenario where we need to post almost 40000 records/sec from our linux boxes to AWS Kinesis. We are planning for multi-process workers(may be 10 workers). Just wondering whether plugin will able to support this much load? and would you guys like to suggest any configuration(may be number of workers and flush parameter) which can help us here.

Any help on this will be really appreciated! Thanks in advance!

**Comment by simukappu** [comment]
I'm sorry but it depend on the use case, for example, the number of servers as data producer, the number of Fluentd agent, cloud-side environment such as the number of Kinesis shards and so on. Please test it on a real environment. The following Performance Turning section in Fluentd document may be helpful.
https://docs.fluentd.org/deployment/performance-tuning-single-process

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
