### ISSUE TITLE
Safe to use over the Internet?

### ISSUE THREAD

**Issue by rami013** [awslabs/aws-fluent-plugin-kinesis#192]
Is this plugin suitable to use over the Internet to send logs in hybrid cloud deployments? In other words, are there any security controls to prevent MITM attacks when sending logs to AWS Kinesis over the Internet if the source systems are not in AWS? I am thinking like DNS poisoning attacks to redirect sources to send their logs to MITM if the client does not properly verify the AWS Kinesis identify/cert?

**Comment by simukappu** [comment]
APIs of AWS services including Amazon Kinesis is HTTPS. The plugin uses AWS SDK and AWS SDK calls HTTPS Kinesis API. The server certificate proves the destination.

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.
