### ISSUE TITLE
google-protobuf recent release 3.12.0 is breaking fluent-plugin-kinesis

### ISSUE THREAD

**Issue by anikoy** [awslabs/aws-fluent-plugin-kinesis#200]
The latest release is dependent on Ruby 2.5 version.

==========
ERROR:  Error installing fluent-plugin-kinesis:
 ==>  google-protobuf requires Ruby version < 2.8.dev, >= 2.5.
==========

**Comment by migimigi** [comment]
I'm using a combination of version 3.1.1 of td-agent and version 2.1.0 of fluent-plugin-kinesis, and I got the same error message.

**Comment by migimigi** [comment]
I tried the workaround in the comments and it installed successfully, thanks.
https://github.com/awslabs/aws-fluent-plugin-kinesis/pull/199#issuecomment-629967114

According to changelog, it is resolved in version 3.2.2.
https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/CHANGELOG.md

Is it my understanding that this error occurs in all environments unless you apply a workaround or update to version 3.2.2, is that correct?

**Comment by anikoy** [comment]
Awesome! version 3.2.2 solves the problem.
