### ISSUE TITLE
Record size limit exceeded in 1883 KB

### ISSUE THREAD

**Issue by Shravankumark** [awslabs/aws-fluent-plugin-kinesis#201]
Hi,

I am running into an issue with kinesis firehose plugin when there is large amount of log data.
I know there is a limitation of 1MB on firehose side.
Can you please help me in resolving the issue?

Config
<match **>
  @type kinesis_firehose
    aws_key_id           
    aws_sec_key              delivery_stream_name prod_firehose
    region               us-east-1
    <buffer>
      flush_thread_count 2
   </buffer>
</match>

Error:
 [error]: #0 Record size limit exceeded in 1883 KB:{"level":"INFO","message":"MMJ.misc.SQSQueue  - PUT /event/v1/putnew Object exceeds the SQS message size limit:, evType:INFOEXCHANGE_UPDATED, activityType: INTEGRATION, subjectID:, posted: 2020-05-25T16:18:09.879Z, , invokedByMainEventQueueProcessor: false\n<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<infoExchange xmlns:ns2=\"urn:MMJ:sit\">\n    <ID></ID>\n    <Operation>MapInToDeliver</Operation>\n    <InputRef>\n        <S3ID></S3ID>\n        <Filename></Filename>\n        <MessageType>CANONICAL</MessageType>\n    </InputRef>\n    <InputSuccessful>true</InputSuccessful>\n    <CanonicalXform>\n        <xFormDateTime>2020-05-25T16:17:57.783Z</xFormDateTime>\n

**Comment by simukappu** [comment]
Closing this issue for now. Please reopen if required.

**Comment by singhajit89** [comment]
No solution/work around found for this issue yet.

**Comment by simukappu** [comment]
Discussing in #210.
