### ISSUE TITLE
Can't use process_credentials without supplying aws_key_id and aws_sec_key

### ISSUE THREAD

**Issue by shkolar-sisense** [awslabs/aws-fluent-plugin-kinesis#205]
Hello,

I don't want to supply key_id and sec_key because it's a security breach for me.
Trying to use the process_credentials feature.
If I use it when supplying key_id and sec_key - it works.
Without them it won't work, the error is:
"Aws::Errors::MissingCredentialsError error="unable to sign request without credentials set".

Now, I can see the response of the process_credentials contains id and secret, so I don't understand why it must be supplied in the configuration as well.
In addition, I can see the error is thrown even before the process_credentials process is called.

Any help will be appreciated.

**Comment by leejh3224** [comment]
If you're running Fluentd on ECS, then you need to add `kinesis:putRecords` into `task role`.
And if it doesn't resolve your issue, upgrading Fluentd from v3.7 to v4.1 resolved the issue.
Old Fluentd is depending on older version of AWS SDK and it may not fetch credentials correctly.
(In case you're using ECS container)
