### ISSUE TITLE
Handle IRSA credentials on kinesis plugins

### ISSUE THREAD

**Issue by cosmo0920** [awslabs/aws-fluent-plugin-kinesis#209]
Currently, fluent-plugin-kinesis does not handle IRSA credentials.
We want to use IRSA mechanism to handle AWS credentials information on EKS cluster.

**Comment by simukappu** [comment]
We've just published as v3.3.0.
https://rubygems.org/gems/fluent-plugin-kinesis/versions/3.3.0

Thank you for your contribution!
