### ISSUE TITLE
Ruby version compatibility issues with aws-sdk-ruby

### ISSUE THREAD

**Issue by kiranbayram** [awslabs/aws-fluent-plugin-kinesis#225]
I think because [aws-sdk-ruby recently dropped support](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-eventstream/CHANGELOG.md#130-2023-11-22) for Ruby 2.3 and 2.4 . 

When I try to install this plugin on a Amazon Linux 2 based AMI, I get the error below:

```
{"changed": true, "cmd": ["td-agent-gem", "install", "fluent-plugin-kinesis"], "delta": "0:01:32.151814", "end": "2023-11-29 16:38:54.215766", "msg": "non-zero return code", "rc": 1, "start": "2023-11-29 16:37:22.063952", "stderr": "ERROR:  Error installing fluent-plugin-kinesis:\n\taws-eventstream requires Ruby version >= 2.5.", "stderr_lines": ["ERROR:  Error installing fluent-plugin-kinesis:", "\taws-eventstream requires Ruby version >= 2.5."], "stdout": "", "stdout_lines": []}
```

**Comment by kiranbayram** [comment]
Sorry if i'm missing sth obvious as I'm not experienced with ruby and gems

**Comment by simukappu** [comment]
This plugin is tested with Ruby 2.4.2 with td-agent v3.1.0, and it has been passed.
https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/.github/workflows/test.yml#L20-L21

Then, we've updated this plugin's dependency to Ruby 2.4.2+.
https://github.com/awslabs/aws-fluent-plugin-kinesis/tree/master?tab=readme-ov-file#dependencies
https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/CHANGELOG.md#350

However, note that the oldest supported Ruby version is v3.0. Ruby 2.x is already EOL.
