### ISSUE TITLE
v0.3.5 plugin is not published to ruby gem

### ISSUE THREAD

**Issue by Jackyjjc** [awslabs/aws-fluent-plugin-kinesis#25]
Could you please publish the gem to ruby-gem please :) we are currently downloading a binary every time which is not very nice. Thank you!

**Comment by imaifactory** [comment]
@Jackyjjc Sorry for kept you waited, I'll work on this, thanks!

**Comment by Jackyjjc** [comment]
@imaifactory thanks you!

**Comment by imaifactory** [comment]
We have published, thanks for waiting!
https://rubygems.org/gems/fluent-plugin-kinesis/versions/0.3.5
