### ISSUE TITLE
Potential memory leak in the plugin

### ISSUE THREAD

**Issue by Jackyjjc** [awslabs/aws-fluent-plugin-kinesis#26]
Hey, I have been using the kinesis plugin to ship logs in production. However, we found that the memory usage of fluentd keep going up even though I'm not using memory buffering (using buffer_type file). This leads to the fluentd get killed by OOM killer. I'm not 100% sure what causes the leak, do you have any insights? I'm using ruby2.2 and kinesis plugin 0.3.5

**Comment by imaifactory** [comment]
@Jackyjjc Thanks for reporting this. At this point of time, I'm not sure so I will look into this.

**Comment by jhappoldt** [comment]
We're also researching a memory leak in this plugin.  Has anyone found anything on this subject?  We'll update if we find the cause but any guidance would be helpful.

**Comment by imaifactory** [comment]
@jhappoldt Thanks for reporting this. At this point of time, I did not reproduce it. Can you elaborate your situation? fluentd/td-agent config, plugin version, ruby version, throughput, velocity of memory leaking and any information would be helpful. Thanks.

**Comment by imaifactory** [comment]
Hmm.. I have run the plugin for 3 days with the configuration below, however I could not reproduce memory leak.

```
<match kinesis.out>
  type kinesis
  stream_name STREAM_NAME
  region us-east-1
  random_partition_key
  retries_on_putrecords 100
  use_yajl true
  buffer_type file
  buffer_path /PATH/TO/FILE
  try_flush_interval 1s
  flush_interval 1s
  buffer_chunk_limit 64m
  buffer_queue_limit 1024
  retry_wait 60s
  max_retry_wait 300s
  retry_limit 4320
</match>
```

**Comment by Jackyjjc** [comment]
Thanks for the helps. I can confirm that the leak is most likely in the in_forward plugin instead of this plugin.

**Comment by imaifactory** [comment]
Thanks for confirmation!
