### ISSUE TITLE
Using KMS encrypted secret key

### ISSUE THREAD

**Issue by jtblin** [awslabs/aws-fluent-plugin-kinesis#27]
We have the kinesis stream that we are writing to in a different account than the clients, and given that the aws-sdk doesn't support using the full ARN for the stream name, we have to distribute access and secret keys instead of IAM roles which is less than ideal. Would you be open to a feature that allow to pass a KMS encrypted secret key using a different variable name e.g. `kms_aws_sec_key` as we could use IAM role policy to decrypt the key and thus avoid leaking the secret? I'd be happy to contribute a PR for that.

**Comment by imaifactory** [comment]
@jtblin Thanks for your comment. Let me think about this.

**Comment by imaifactory** [comment]
@jtblin  Thank you for waiting. 

I have thought about the idea you suggested. Even if we use `kms_aws_sec_key`, we have to [decrypt](http://docs.aws.amazon.com/kms/latest/APIReference/API_Decrypt.html) it with properly delegated IAM user/role, and stored the decrypted plain secret key in the process. It means secret key can be leaked if we put some debug method into the code.

Another idea is to use [AssumeRole](http://docs.aws.amazon.com/sdkforruby/api/Aws/STS/Client.html#assume_role-instance_method). This is a clean solution, however we need to run token vending machine in the account of Kinesis Stream holder. ( and of course we need some tweak to this plugin ). 

Thus, how about create a dedicated IAM user for Kinesis data ingestion which can only do data ingestion to Kinesis, then distribute the AK/SK to producers? It might be what you are doing currently though, it looks reasonable solution to me.

**Comment by jtblin** [comment]
@imaifactory yes you need to decrypt the keys but that can be done using an IAM role as it can be encrypted in the same account as the client. The secret key could still be leaked if someone modify the code to display it so it is not entirely bullet proof but it's OK in my opinion. Our use case is that these keys are deployed on hundreds of instances for internal services and I'm not looking for a perfect solution but protect against basic leakage of the credentials which is the case as of now. 

AssumeRole seems like a great option, but it only returns credentials valid for one hour. I guess you could make it so that it gets new credentials before they expire?

Re: dedicated users, as mentioned above we have hundreds of services so creating one user per service is not a valid option in our case, and rotating the credentials would be hard to manage.

Note that this issue is mostly due to kinesis not supporting passing the full ARN instead of the stream name, so if this is fixed soon then the issue would disappear for us, but at the moment it is a serious problem for us.

Happy to look into the AssumeRole more, or is it something that you'd be likely to do? If not do you have any particular design guideline in mind?

**Comment by imaifactory** [comment]
@jtblin 

> AssumeRole seems like a great option, but it only returns credentials valid for one hour. I guess you could make it so that it gets new credentials before they expire?

Yes. AssumeRole support to provide credential valid for 1 hour at maximum. So we need to refresh credentials continuously in the plugin. But I think this is reasonable and right way.

In this case, the configuration would be like this

```
<match test.source>
    type kinesis
    stream_name STREAM
    region us-east-1
    flush_interval 1
    random_partition_key
    
    role_arn YOUR_ROLE_TO_BE_ASSUMED

</match>
```

I have a question for you.
http://docs.aws.amazon.com/IAM/latest/UserGuide/roles-walkthrough-crossacct.html
We can find the steps in the web page above, you need to configure `trust policy` from kinesis stream holder account to each client accounts. Is this reasonable for you?

**Comment by jtblin** [comment]
Yes that would be totally reasonable. And it looks like the ruby aws-sdk already handles auto refreshing the token so should be fairly simple: https://github.com/aws/aws-sdk-ruby/issues/520.

**Comment by imaifactory** [comment]
I will leave this open until RubyGems will be released.

**Comment by imaifactory** [comment]
Thank you for waiting. We have released.
https://rubygems.org/gems/fluent-plugin-kinesis/versions/0.3.6

**Comment by jtblin** [comment]
Thanks @imaifactory :+1:
