### ISSUE TITLE
0.3.6 is not on rubygems

### ISSUE THREAD

**Issue by wryun** [awslabs/aws-fluent-plugin-kinesis#30]
https://rubygems.org/gems/fluent-plugin-kinesis/versions/

Would be great it is was - thanks!

**Comment by imaifactory** [comment]
@wryun 
I'm working on this. However it may take few more days. Thanks for waiting.

**Comment by wryun** [comment]
Looks like it's there - thanks :+1:

**Comment by imaifactory** [comment]
Thanks!
