### ISSUE TITLE
Can not install plugin

### ISSUE THREAD

**Issue by yusufcangurkan** [awslabs/aws-fluent-plugin-kinesis#31]
I install plugin for td-agent as you wrote on documentation but when i run "td-agent -c file.conf" it says, the plugin kinesis could not find. What am i missing?

**Comment by imaifactory** [comment]
@yusufcangurkan 

It looks like you did not install. Can you check it with `fluent-gem list installed`?
If `fluent-plugin-kinesis` does not appear on the list, it is not installed properly.
If it appears, please provide full stack trace for your runtime.

Thanks!

**Comment by yusufcangurkan** [comment]
@imaifactory 

Thanks for reply. When i run that command:

fluent-gem list installed

*** LOCAL GEMS ***


It does not print any plugin as you see but i use and installed bunch of plugins before. Also, i install this plugin with commands you put on readme file and it says successfully installed. However, when i check plugins in fluentd's gem folder this plugin does not exist.

**Comment by imaifactory** [comment]
Thanks! It looks like your to-agent bundled ruby does not have any plugins.

How did you installed the plugins previously? Did you try that way?
2015年9月8日(火) 18:07 Yusuf Can Gürkan <notifications@github.com>:

**Comment by yusufcangurkan** [comment]
Hello,

I installed previous plugins on fluentd-ui and i did not install any plugin with another way. I think this is the problem, fluentd-gem does not see the same place that i use for td-agent may be?

**Comment by imaifactory** [comment]
It looks like so. I have experience, but could you try install the plugin
in that way? We are providing the plugin via RubyGems as other plugins do,
it might work.

2015年9月8日(火) 23:40 Yusuf Can Gürkan <notifications@github.com>:

**Comment by yusufcangurkan** [comment]
In what way ? I already tried to install with "fluentd-gem install ..." for a couple of times. It says it was installed successfully but td-agent doesnt see it.

**Comment by imaifactory** [comment]
Ah forgive me about previous post. Could you try in fluentd-hi?
2015年9月8日(火) 23:50 Yusuf Can Gürkan <notifications@github.com>:

**Comment by yusufcangurkan** [comment]
I can not try it with fluentd-ui because this plugin is not listed on its plugin list. That's why i tried to install it manually but could not manage it.

**Comment by imaifactory** [comment]
OK, I will look into it.

**Comment by imaifactory** [comment]
@yusufcangurkan 

Please try `sudo /usr/sbin/td-agent-gem install fluent-plugin-kinesis`.

**Comment by riywo** [comment]
@yusufcangurkan 

I'm going to close this. If you have any update, feel free to re-open it.
