### ISSUE TITLE
Emits entire record on error

### ISSUE THREAD

**Issue by wryun** [awslabs/aws-fluent-plugin-kinesis#32]
There are a couple of situations in this plugin where the record data is logged on failure. If the fluentd logs are also sent to the kinesis stream, this can cause problems, since the reason the record failed might be to do with the record itself (i.e. too large) and an even larger record will be generated.

Thus an endless loop of 'failed' records ensues, each one progressively larger.

Perhaps the record can be trimmed before being logged?

**Comment by wryun** [comment]
Or maybe there could be an option to disable output on errors from single log lines (it's always problematic (?) ) and instead output an aggregate error logline from each chunk.

**Comment by imaifactory** [comment]
@wryun 

Thanks for bringing up this. The plugin and Kinesis Stream now allow up to 1MB for each record(https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/lib/fluent/plugin/out_kinesis.rb#L31), so I don't think size of each single log line makes problem. However I should look into.

In parallel, if you are not using the latest version of the plugin, can you update? The limit size has been updated from 50KB to 1MB at [version0.3.5](https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/CHANGELOG.md#035).

Thanks!

**Comment by wryun** [comment]
We are using the latest version... believe it or not, this happened to us on a >1mb record :) (we can't control our users easily!)

**Comment by imaifactory** [comment]
hmm... I don't want this plugin to trim data, so shortening or summarising log?
The log emitting you are facing problem is here? 
https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/lib/fluent/plugin/out_kinesis.rb#L127

**Comment by wryun** [comment]
Sorry, yes, that's what I meant (error logline should be trimmed or summarised). Definitely should fail on logline.

Yes, that is the problem. But I also worry about any 1-to-1 log emission, since it means failures will roll on indefinitely unless you take care to ship the fluentd internal log to a separate output (i.e. line fails, generates 1st error logline, that error logline fails, etc.). I guess one solution could be to just put a recommendation to match on match fluentd.** and make sure to not use Kinesis. I feel like something is broken in the fluentd model here, so maybe there's something I'm missing about how to work around it.

**Comment by imaifactory** [comment]
@wryun 

Thanks for following up! Understood your concern. Next week, I will do some log summarising first.

**Comment by imaifactory** [comment]
Also I will try this in next day.

**Comment by riywo** [comment]
v1.0.0 truncates error log message by 200 chars (will be configurable in later version).

**Comment by wryun** [comment]
Thanks!
