### ISSUE TITLE
Parallelism and throughput question

### ISSUE THREAD

**Issue by rajpannu** [awslabs/aws-fluent-plugin-kinesis#4]
I setup fluent to ingest nginx logs into Kinesis using this plugin and I am trying to configure it to keep up with the throughput.  I have around 30-40 log events per second, which seems reasonable.   
  
I have the Kinesis stream set for 2 shards, which should be enough and the Amazon monitoring does not show any issues (write capacity and read capacity usage are reading near zero).     
  
I setup two EC2 xlarge machines.  The nginx processes and disk usage have absolutely no problems keeping up.  Nginx logs show in real time.   Each machine has td-agent running.  Tweaking this seems to be where the problem is.  I have tried with detach_process 1 through 4, and all kinds of values for num_threads.   I also tried setting it to random_partition_key true  
  
No matter what I try the CPU is not saturated and the ruby processes can't seem to keep up.  During higher loads (around 40 events per second, or 20 per second per machine) it falls to 20 or 30 minutes behind. 
  
Are there any recommended settings tweaks that I can try, or possibly more machines for network throughput, or is this expected for this load to kinesis?

**Comment by imaifactory** [comment]
Closing due to no update.
