### ISSUE TITLE
Link to official documentation

### ISSUE THREAD

**Issue by kzk** [awslabs/aws-fluent-plugin-kinesis#47]
Hi @riywo,

I just wrote an official documentation for this plugin (http://docs.fluentd.org/articles/kinesis-stream). Can I ask you to add the link from this repository?

**Comment by riywo** [comment]
done! https://github.com/awslabs/aws-fluent-plugin-kinesis/commit/c84e5069d284169f8a86cabfbb4da1d29e44ec0e
