### ISSUE TITLE
Urgent query on deploying the plugin without internet connection

### ISSUE THREAD

**Issue by iamhasibrahman** [awslabs/aws-fluent-plugin-kinesis#52]
Thanks for your outstanding help in other queries. 

I've got a question on deploying your plugin on source that has no internet connection ...

Let me describe the situation --- The source is in totally closed area so we need to download the td-agent and your plugin in a separate box, and then move those two to source. But your plugin requires other package such as this -- 

./fluent-gem install fluent-plugin-kinesis

This will fetch some files: (Do these need to be manually downloaded??)
Fetching: jmespath-1.1.3.gem 
Fetching: aws-sdk-core-2.2.20.gem
 Fetching: fluent-plugin-kinesis-0.4.0.gem

So our understanding is that we need to manually download the file and build the plugin before move to source. So we did the below -

curl -O  https://rubygems.org/gems/aws-sdk-core/versions/2.2.20
and then td-agent-gem 2.2.20 --- but didn't work. 

So you see we are in the zone of dependency hell, what would be your recommendations to build the plugin as one package so we can deploy to source (that doesn't have internet connection)

**Comment by riywo** [comment]
Hi,

It is not related to only this plugin. The problem is a general question about fluentd, that is how to install plugin without internet. Please ask it to fluentd user ML. http://docs.fluentd.org/articles/mailing-list

You can also consider to use [Kinesis Agent](http://docs.aws.amazon.com/kinesis/latest/dev/writing-with-agents.html) to send logs to Amazon Kinesis Streams. It is built on Java so that you can build one package jar file.

**Comment by iamhasibrahman** [comment]
Kinesis Agent as far as I know doesn't work on RHEL 5.3 (the OS source system)

**Comment by iamhasibrahman** [comment]
I perhaps confused you with long e-mails. We were able to install fluentd agent (td-agent in fact) just fine. Here is what I did - Obviously, we just downloaded the agent on a machine that has internet and then move to the source. 

But your plugin requires 3 gems --- 

Fetching: jmespath-1.1.3.gem
 Fetching: aws-sdk-core-2.2.20.gem
 Fetching: fluent-plugin-kinesis-0.4.0.gem

Can we download them from ruby gems like the below - 
curl -O  https://rubygems.org/gems/aws-sdk-core/versions/2.2.20
and then place them under certain folder..most of them are AWs packAGES RIGHT?

**Comment by riywo** [comment]
You can try this http://stackoverflow.com/a/9312332/2052892 .

I'm sorry but this repository is plugin only. If you have question about fluentd itself, you should ask it to the fluentd community like fluentd GitHub repository or the mailing list.

**Comment by iamhasibrahman** [comment]
About fluentd - actually question was on deploying plugin... Not on fluentd. But anyway, you'd link that you shared is the approach I took ... Super helpful. Thanks a lot. Really appreciate. Hope to run it soon.  Will chat later.

**Comment by riywo** [comment]
I think plugin deployment is a part of fluentd so that you can ask it to the community.
