### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by iamhasibrahman** [awslabs/aws-fluent-plugin-kinesis#53]
When we use proxy, this is what will happen, right?

Fluent-plugin-Kinesis is writing to our proxy in cleartext (no SSL) and then the proxy is sending it up to Kinesis via SSL, correct. 

So we need to handle SSL from Proxy server to AWS Kinesis regional end point??

**Comment by riywo** [comment]
No. Ruby stdlib Net::HTTP (which is used by AWS SDK for Ruby) uses CONNECT command to order the proxy to create TCP tunnel to remote SSL server. After that, all communication is encrypted. Please tcpdump packets to verify it.

https://en.wikipedia.org/wiki/HTTP_tunnel#HTTP_CONNECT_tunneling
https://github.com/ruby/ruby/blob/ec0198fd8cfee7ae499602235fcf3a9318f9b691/lib/net/http.rb#L911-L920

If your proxy server doesn't support CONNECT command, I don't know how to solve that problem. Please ask to AWS Forum for Ruby development.

https://forums.aws.amazon.com/forum.jspa?forumID=125

**Comment by iamhasibrahman** [comment]
This is extremely useful. Really appreciate it.
