### ISSUE TITLE
deploy version 1.0 plugin on system without internet

### ISSUE THREAD

**Issue by iamhasibrahman** [awslabs/aws-fluent-plugin-kinesis#59]
Hi All - 

We're getting below error message when we try to download the plugin on a temp server ....idea is to move those gems on actual source that has no internet connection. 

It worked with Version .4, but giving the below error message for version 1.0 

Question - should I just grab active support manually or this could be something bigger than just simply grabbing a gem manually. Please advise. 

Step 1 grab td-agent

curl -O http://packages.treasuredata.com.s3.amazonaws.com/2/redhat/5/i386/td-agent-2.2.1-0.el5.i386.rpm

Step 2  Install td-agent
rpm -ivh td-agent-2.2.1-0.el5.i386.rpm

Step 3 grab all the fluentd-agent related gem

 td-agent-gem install fluent-plugin-kinesis -i repo --no-rdoc --no-ri 

While doing step 3, it failed as —

ERROR: Error installing fluent-plugin-kinesis:
activesupport requires Ruby version >= 2.2.2.

**Comment by riywo** [comment]
Could you paste whole error log?

**Comment by riywo** [comment]
Of course its dependency has been changed from 0.4 to 1.0, you should grub new dependencies if you have not done yet.

**Comment by iamhasibrahman** [comment]
Yes, I'm aware that the dependency has changed. 

And the purpose the below command is to get the new dependency --
td-agent-gem install --version '> 0.3.2 fluent-plugin-kinesis -i repo --no-rdoc --no-ri

And with the version -4.0, the above command is all that I needed to get all the gem. But now it's not working and it's providing the error. That's the only error message, don't have any other log.

**Comment by iamhasibrahman** [comment]
Sorry, the command was wrong -- typo. Here is the right one ---

td-agent-gem install fluent-plugin-kinesis -i repo --no-rdoc --no-ri

**Comment by iamhasibrahman** [comment]
As a temporary solution, we switched back to older version as our production test deployment is not so far away. 

Here is the command we used - 

td-agent-gem install fluent-plugin-kinesis  -i repo --no-rdoc --no-ri -v "< 1"

**Comment by iamhasibrahman** [comment]
I ran it again and I'm providing you the whole steps -- 

1. Download td-agent 

curl -O http://packages.treasuredata.com.s3.amazonaws.com/2/redhat/5/i386/td-agent-2.2.1-0.el5.i386.rpm

2. install td-agent
rpm -ivh td-agent-2.2.1-0.el5.i386.rpm

3. Get fluent-output-plugin   -- look at the last line. It's trying to get beta version of active support and then failing...
[root@ip-172-31-6-190 downloads]# td-agent-gem install fluent-plugin-kinesis -i repo --no-rdoc --no-ri
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.4.3)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Fetching: cool.io-1.4.3.gem (100%)
Building native extensions.  This could take a while...
Successfully installed cool.io-1.4.3
Fetching: http_parser.rb-0.6.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed http_parser.rb-0.6.0
Fetching: json-1.8.3.gem (100%)
Building native extensions.  This could take a while...
Successfully installed json-1.8.3
Fetching: msgpack-0.7.4.gem (100%)
Building native extensions.  This could take a while...
Successfully installed msgpack-0.7.4
Fetching: sigdump-0.2.4.gem (100%)
Successfully installed sigdump-0.2.4
Fetching: strptime-0.1.6.gem (100%)
Building native extensions.  This could take a while...
Successfully installed strptime-0.1.6
Fetching: thread_safe-0.3.5.gem (100%)
Successfully installed thread_safe-0.3.5
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: tzinfo-data-1.2016.3.gem (100%)
Successfully installed tzinfo-data-1.2016.3
Fetching: yajl-ruby-1.2.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed yajl-ruby-1.2.1
Fetching: fluentd-0.14.0.pre.1.gem (100%)
Successfully installed fluentd-0.14.0.pre.1
Fetching: concurrent-ruby-1.0.1.gem (100%)
Successfully installed concurrent-ruby-1.0.1
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: minitest-5.8.4.gem (100%)
Successfully installed minitest-5.8.4
Fetching: activesupport-5.0.0.beta3.gem (100%)
ERROR:  Error installing fluent-plugin-kinesis:
	activesupport requires Ruby version >= 2.2.2.

**Comment by iamhasibrahman** [comment]
Just published detail logs …

**Comment by riywo** [comment]
Thank you for the information. It will be a bug of td-agent 2.2.1 and 2.3.0 since I could reproduce this on my machine.

I also tried the latest td-agent (2.3.1) and there is no error. So, could you try 2.3.1?

**Comment by iamhasibrahman** [comment]
Does the td-agent version 2.3.1 available for RHEL 5.1?

**Comment by iamhasibrahman** [comment]
Final interim solution - we'll switch back to version .4 ..

td-agent-gem install fluent-plugin-kinesis -i repo --no-rdoc --no-ri -v "< 1"

**Comment by riywo** [comment]
Of course you can use 0.4 but in the future there will be no update for v0.x. I recommend to update to v1.0.

**Comment by iamhasibrahman** [comment]
Below seemed to work, does that make sense -- 

------- This is the command history where fluentd installed successfully with td-agent version 2.1 (32 bit)

 

    curl -O http://packages.treasuredata.com.s3.amazonaws.com/2/redhat/5/i386/td-agent-2.2.1-0.el5.i386.rpm
    rpm -ivh td-agent-2.2.1-0.el5.i386.rpm



    td-agent-gem install activesupport  -i repo --no-rdoc --no-ri
    cd repo
    cd cache


   td-agent-gem install --force --local *.gem

   td-agent-gem install fluent-plugin-kinesis -i repo --no-rdoc --no-ri

   cd repo
   cd cache
   td-agent-gem install --force --local *.gem

**Comment by riywo** [comment]
I'd like to keep this open until the root cause is investigated. I opened an issue on td-agent repo.

**Comment by iamhasibrahman** [comment]
Just a note --
It's again acting strange --- download pre-release gem when I did TD-agent-gem .. If I manually download that, it works. But as you would agree, manually download individual gem is scary. 

--
{...Hasib +61 432 745 136)




On Mon, Mar 28, 2016 at 11:47 PM -0700, "Ryosuke IWANAGA" <notifications@github.com> wrote:












I'd like to keep this open until the root cause is investigated. I opened an issue on td-agent repo.

**Comment by riywo** [comment]
As I thought, it is caused by old rubygems. If you update td-agent-gem before install, there is no error.

See https://github.com/treasure-data/omnibus-td-agent/issues/73

````
# td-agent-gem -v
2.2.1
# td-agent-gem update --system
# td-agent-gem -v
2.6.2
# td-agent-gem install fluent-plugin-kinesis -i repo --no-rdoc --no-ri
Fetching: thread_safe-0.3.5.gem (100%)
Successfully installed thread_safe-0.3.5
Fetching: thor-0.19.1.gem (100%)
Successfully installed thor-0.19.1
Fetching: middleware-0.1.0.gem (100%)
Successfully installed middleware-0.1.0
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: minitest-5.8.4.gem (100%)
Successfully installed minitest-5.8.4
Fetching: json-1.8.3.gem (100%)
Building native extensions.  This could take a while...
Successfully installed json-1.8.3
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: activesupport-4.2.6.gem (100%)
Successfully installed activesupport-4.2.6
Fetching: protobuf-3.6.7.gem (100%)
Successfully installed protobuf-3.6.7
Fetching: os-0.9.6.gem (100%)
Successfully installed os-0.9.6
Fetching: yajl-ruby-1.2.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed yajl-ruby-1.2.1
Fetching: tzinfo-data-1.2016.3.gem (100%)
Successfully installed tzinfo-data-1.2016.3
Fetching: string-scrub-0.0.5.gem (100%)
Building native extensions.  This could take a while...
Successfully installed string-scrub-0.0.5
Fetching: sigdump-0.2.4.gem (100%)
Successfully installed sigdump-0.2.4
Fetching: msgpack-0.5.12.gem (100%)
Building native extensions.  This could take a while...
Successfully installed msgpack-0.5.12
Fetching: http_parser.rb-0.6.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed http_parser.rb-0.6.0
Fetching: cool.io-1.4.3.gem (100%)
Building native extensions.  This could take a while...
Successfully installed cool.io-1.4.3
Fetching: fluentd-0.12.22.gem (100%)
Successfully installed fluentd-0.12.22
Fetching: concurrent-ruby-1.0.1.gem (100%)
Successfully installed concurrent-ruby-1.0.1
Fetching: jmespath-1.1.3.gem (100%)
Successfully installed jmespath-1.1.3
Fetching: aws-sdk-core-2.2.30.gem (100%)
Successfully installed aws-sdk-core-2.2.30
Fetching: aws-sdk-resources-2.2.30.gem (100%)
Successfully installed aws-sdk-resources-2.2.30
Fetching: aws-sdk-2.2.30.gem (100%)
Successfully installed aws-sdk-2.2.30
Fetching: fluent-plugin-kinesis-1.0.0.gem (100%)
Successfully installed fluent-plugin-kinesis-1.0.0
24 gems installed
````

**Comment by iamhasibrahman** [comment]
:) :) Quite an irony for us...the reason being, our deployment involves source system without internet..not sure how I can update the gem on temp machine and then move to actual source without internet. I will take this matter with TD team. Thanks.

**Comment by iamhasibrahman** [comment]
I found a way out of td-agent-gem version issue, and here is the solution. That said, working with TD team to ensure this is the only solution, or something better possible. 

 ## ON MACHINE 1 (with internet)

        # download and install td-agent
        curl -O http://packages.treasuredata.com.s3.amazonaws.com/2/redhat/5/i386/td-agent-2.2.1-0.el5.i386.rpm
        rpm -ivh td-agent-2.2.1-0.el5.i386.rpm

        # Update td-agent-gem  
        td-agent-gem -v  # should return 2.2.1
        td-agent-gem update --system
        td-agent-gem -v  # should return 2.2.12.6.

        # Manually download fluent-plugin  
        td-agent-gem install fluent-plugin-kinesis -i repo --no-rdoc --no-ri
        # all gems will be downloaded ...your present working directory/repo/cache

        # zip all gems that you just downloaded for second machine. 
        cd repo
        cd cache
        zip fluent-kinesis *.gem
       
        # Verify zip contains all the gem
        zipinfo -1 fluent-kinesis.zip

    ## ON MACHINE 2   (without internet) 

        # Move rpm to the second machine and install 
        rpm -ivh td-agent-2.2.1-0.el5.i386.rpm

        # move/upoad the zipped gems (the kinesis output plugin fluent-kinesis) and unzip  
        unzip fluent-kinesis.zip

        # install fluent-kinesis output plugin  
        td-agent-gem install --force --local *.gem
        ## NOTE: We're using td-agent-gem version 2.2.1 to install (on machine 2) whereas 
        ## We used td-agent-gem version 2.6.2 to fetch the gems (on machine 1).
