### ISSUE TITLE
Derive stream name from fluentd tag

### ISSUE THREAD

**Issue by cbroglie** [awslabs/aws-fluent-plugin-kinesis#67]
We have an application where we would like to route data to different Kinesis streams based on the fluentd tag. This is doable by specifying a different `<match></match>` configuration for each tag, but it means that there will be a separate KPL process for each configuration. And if we have 20 different streams, that means 20 instances of the KPL process, which wastes resources.

Since the KPL requires the stream name to be specified with each record, the fluentd plugin can dynamically determine the stream name for each record it processes. One possible way to do this would be to allow users to specify a stream name prefix, and a regex to extract other data from the tag. A simpler (and more efficient) alternative would be a simple concatenation.

I'm happy to provide a PR for this functionality, if there is interest in accepting it.

**Comment by riywo** [comment]
Hi @cbroglie ,

I've released v1.1.0 and it contains this contribution. Thank you for your PR!
https://rubygems.org/gems/fluent-plugin-kinesis/versions/1.1.0

**Comment by cbroglie** [comment]
Thanks!
