### ISSUE TITLE
Gem Dependency Conflict

### ISSUE THREAD

**Issue by bratislavml** [awslabs/aws-fluent-plugin-kinesis#77]
Hi, after plugin installation I am getting following error:

/opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2064:in `raise_if_conflicts': Unable to activate aws-sdk-2.1.36, because aws-sdk-resources-2.2.3 conflicts with aws-sdk-resources (= 2.1.36) (Gem::LoadError)
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1262:in `activate'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1298:in `block in activate_dependencies'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1284:in `each'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1284:in `activate_dependencies'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1266:in `activate'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:196:in `rescue in try_activate'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:193:in `try_activate'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-firehose-0.1.1/lib/fluent/plugin/out_kinesis_firehose.rb:1:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin.rb:168:in `block in try_load_plugin'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin.rb:166:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin.rb:166:in `try_load_plugin'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin.rb:126:in `new_impl'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin.rb:57:in `new_output'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin/out_copy.rb:41:in `block in configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin/out_copy.rb:34:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/plugin/out_copy.rb:34:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/agent.rb:129:in `add_match'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/agent.rb:60:in `block in configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/agent.rb:54:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/agent.rb:54:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/root_agent.rb:82:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/engine.rb:116:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/engine.rb:90:in `run_configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:497:in `run_configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:145:in `block in start'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:336:in `call'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:336:in `main_process'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:311:in `block in supervise'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:310:in `fork'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:310:in `supervise'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/supervisor.rb:141:in `start'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/lib/fluent/command/fluentd.rb:171:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.17/bin/fluentd:6:in `<top (required)>'
	from /opt/td-agent/embedded/bin/fluentd:23:in `load'
	from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
	from /usr/sbin/td-agent:7:in `load'
	from /usr/sbin/td-agent:7:in `<main>'
                                                           [FAILED]
2016-07-14 11:19:28 -0400 [info]: process finished code=256
2016-07-14 11:19:28 -0400 [warn]: process died within 1 second. exit.
^C[1]+  Exit 1                  service td-agent start

This is td-agent version:

/etc/td-agent/conf.d]# yum info td-agent
Loaded plugins: priorities, update-motd, upgrade-helper
959 packages excluded due to repository priority protections
Installed Packages
Name        : td-agent
Arch        : x86_64
Version     : 2.2.1
Release     : 0.el2015
Size        : 199 M
Repo        : installed
From repo   : treasuredata
Summary     : Treasure Agent: A data collector for Treasure Data
URL         : http://treasuredata.com
License     : unknown
Description : Treasure Agent: A data collector for Treasure Data

Could you please help about this?

Thanks

**Comment by brad-hays-mentor** [comment]
I have also seen this, have not had time to troubleshoot though.

**Comment by riywo** [comment]
Hi,

The error is raised by fluent-plugin-kinesis-firehose, not this plugin. Please uninstall fluent-plugin-kinesis-firehose gem and try again.

Best

**Comment by riywo** [comment]
I'd like to close this issue since this is not an issue of this plugin. If you have additional question, feel free to add more comments here.
