### ISSUE TITLE
Removing message and time 

### ISSUE THREAD

**Issue by bratislavml** [awslabs/aws-fluent-plugin-kinesis#78]
Hi,

How can I remove message and time field below keeping only json {\"transactionId\":\"221620499\",....} in the message forwarded to kinesis forehose?

{
    "message": "\r{\"transactionId\":\"221620499\",....}",
    "time": "2016-07-20T10:58:50-04:00"
}

Thanks

**Comment by riywo** [comment]
Hi,

Could you provide a related part of your fluent.conf?

Best

**Comment by bratislavml** [comment]
Thank you riywo for quick reply. Here is the part for td-agent.conf:
...
  <store>
      type kinesis_firehose

      delivery_stream_name <name>

      #credentials
      aws_key_id *******
      aws_sec_key *******
      region us-east-1

      include_time_key true
      flush_interval 5s
  </store>
...

Does include_time_key affect message structure? I can remove it.

**Comment by riywo** [comment]
Yes,  the time key in your output comes from `include_time_key true`. I'm not sure how the `message` field comes from.

If your original record has the `message` field, then you can use `data_key message` instead.

**Comment by bratislavml** [comment]
Thanks riywo, using data_key message was working.

**Comment by riywo** [comment]
Good to hear that. If you have questions more, feel free to add more comments here.
