### ISSUE TITLE
Data is based64 encoded twice

### ISSUE THREAD

**Issue by czchen** [awslabs/aws-fluent-plugin-kinesis#8]
The data put to Kinesis seem to be base64 encoded twice. When using <https://github.com/awslabs/amazon-kinesis-client-python> to get data from Kinesis stream put by this plugin, I need to use the following python code to get my JSON data correctly.
```
data = base64.b64decode(base64.b64decode(record.get('data')))
```
If I use <https://github.com/boto/boto> to put data into Kinesis, the following code is sufficient to get my JSON data correctly.
```
data = base64.b64decode(record.get('data'))
```
The following is content of td-agent.conf
```
<match extracted.*.*>
  type kinesis

  stream_name <censored>
  aws_key_id <censored>
  aws_sec_key <censored>
  region <censored>

  random_partition_key true
</match>
```

**Comment by czchen** [comment]
@mstoops I use the following code to workaround this issue. Maybe you can do the same.

```
data = base64.b64decode(record.get('data'))
try:
    res = json.loads(data)
except ValueError:
    data = base64.b64decode(data)
    res = json.loads(data)

```

**Comment by mstoops** [comment]
@czchen, than you very much. It is a decent work-around until the project is updated.

**Comment by imaifactory** [comment]
Thank for your waiting. We have removed redundant base64 encoding in a new release. 

https://github.com/awslabs/aws-fluent-plugin-kinesis/commit/d5f38521b17c9b2b7b0ab09c61a2cf781a216d0f#diff-b19e4edd33848b9b655b051dd552cb0cL86

**Comment by mstoops** [comment]
Thank you!
