### ISSUE TITLE
TLS/Ciphers

### ISSUE THREAD

**Issue by EyesOfRaistlinV** [awslabs/aws-fluent-plugin-kinesis#91]
Hello,

   I am trying to find out what version of TLS, and what cipher (specifically) are used by this plugin when connecting to Kinesis Streams.  Is that documented somewhere? 

Thank you,
J.W.

**Comment by twosider** [comment]
The short answer is ECDHE-RSA-AES128-SHA. There are ways to override the cipher, but this is rare in practice. 

According to this, https://github.com/aws/aws-sdk-ruby/issues/683 , aws ruby sdk v2 is using the default for Net::HTTP.

I found this for IoT, but not Kinesis: http://docs.aws.amazon.com/iot/latest/developerguide/iot-security-identity.html

**Comment by EyesOfRaistlinV** [comment]
Ben,

   Thank you.  I will look at the defaults in the aws ruby sdk.

J.W.

*Jerod A. Weaver*
Valiant Solutions, LLC
c:  816.398.5770
jweaver@valiantsolutions.com
www.valiantsolutions.com
