### ISSUE TITLE
random_partition_key parameter not being used?

### ISSUE THREAD

**Issue by eoconnor** [awslabs/aws-fluent-plugin-kinesis#97]
I just noticed the following warnings in my Fluentd logs:

```
2017-01-13 07:04:17 +0000 [warn]: parameter 'random_partition_key' in <match **>
  @id out_kinesis_events
  @type kinesis_producer
  region us-west-2
  stream_name myCoolStream
  buffer_chunk_limit 1m
  buffer_queue_limit 1000
  buffer_type file
  buffer_path /mnt/aggregator.*.buffer
  flush_interval 1
  try_flush_interval 0.1
  queued_chunk_flush_interval 0.01
  random_partition_key true
  num_threads 15
  detach_process 5
  <kinesis_producer>
    metrics_namespace myCoolMetrics
  </kinesis_producer>
  <secondary>
    @id out_file_failed_kinesis
    @type file
    path /var/log/td-agent/failed_kinesis_writes
    append true
    buffer_path /var/log/td-agent/failed_kinesis_writes.*
  </secondary>
</match> is not used.
```
If I'm to interpret that literally, it looks like Fluentd isn't recognizing my random_partition_key? I'm not sure why that would be; from looking at the documentation and plugin source code, it looks like I'm using it correctly. Any ideas?

**Comment by tehranian** [comment]
I think you misunderstood the docs. There is no such option as `random_partition_key`, but there is an option called `partition_key`. If you leave that option as the default (`nil`), then it will use a random partition key. See: https://github.com/awslabs/aws-fluent-plugin-kinesis#partition_key-1

It looks like you're trying to have a random partition key, so given that you've not overridden `partition_key`, Fluentd is currently working as you desire. This warning simply serves to let you know that the configuration `random_partition_key true` is having no effect.

**Comment by eoconnor** [comment]
Thanks for the quick response. I see now that random_partition_key is not listed in the README documentation. It is in the source code, however (https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/lib/fluent/plugin/out_kinesis.rb), and also mentioned in an article on the plugin on the Fluentd site (http://docs.fluentd.org/articles/kinesis-stream). So, maybe some mixed messages there. But it sounds like the lack of a partition_key parameter is all I need to ensure the functionality I want. So, thanks!

**Comment by tehranian** [comment]
@eoconnor : Oh wow. Thanks for the links. I guess the source code is the real source of truth here! :)

**Comment by riywo** [comment]
Hi @eoconnor ,

In kinesis_stream and kinesis_producer plugins, random_partiton_key has been removed and that is the default behavior unless you specify your partition key. So, you're right.

You're trying to use kinesis_producer plugin, so your pointing source is wrong. And kinesis type plugin is deprecated, so fluentd doc should be updated to use kinesis_stream plugin. We'll delete this plugin in the next release.

Best,
