### ISSUE TITLE
compressing output to kinesis_streams

### ISSUE THREAD

**Issue by rgarcia** [awslabs/aws-fluent-plugin-kinesis#98]
I see the deprecated `kinesis` type has a `zlib_compression` option, but that `kinesis_streams` does not have this option. What's the recommended way to compress data sent through `kinesis_streams`?

**Comment by riywo** [comment]
Unfortunately, it is not supported right now. If you need this feature, feel free to create a PR.

To prioritize, I'd like to understand what is the use case for compression.

**Comment by rgarcia** [comment]
@riywo a Kinesis stream charges/limits you based off of throughput in bytes. Compression saves bytes, which lets you send more data to a stream and also saves money 😄

**Comment by riywo** [comment]
Got it. It totally makes sense. I'll try to make it in version 2.0.0.

**Comment by leamarty** [comment]
+1

**Comment by riywo** [comment]
#112
